- name: Import OS-specific variables
  include_vars: "{{ item }}"
  failed_when: false
  loop:
    - "{{ ansible_os_family | lower }}-based.yml"
    - "{{ ansible_os_family | lower }}-based-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.split('.')[0:2] | join('-') | lower }}.yml"

- name: Ensure packages are installed
  package:
    name: "{{ mysql_packages }}"
    state: present

- import_tasks: setup.yml
- import_tasks: users.yml
- include_tasks: database.yml
  loop: "{{ mysql_databases }}"
