- name: Ensure nginx is installed
  package:
    name: nginx

- name: Ensure sites-* directories are not present
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available

- name: Ensure http user exists
  user:
    name: "{{ http_user }}"
    shell: /bin/nologin

- name: Ensure hosts directory exists
  file:
    path: "{{ hosts_dir }}"
    state: directory

- name: Ensure www directory exists
  file:
    path: "{{ www_dir }}"
    mode: 0700
    state: directory
    owner: "{{ http_user }}"
    group: "{{ http_user }}"

- name: Ensure config file is installed
  template:
    src: nginx.conf
    dest: /etc/nginx
  notify: Restart nginx
